#!/usr/bin/env python
# Copyright (C) 2025 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""pytest hooks."""

import argparse

import pytest


def pytest_addoption(parser: pytest.Parser) -> None:
    """Add command line options to pytest."""
    parser.addoption(
        "--copy-coverage",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="copy the coverage file generated by the injected tests to .coverage in the root directory",
    )
